version: "3"

services:
  database:
    image: postgres:buster
    container_name: database
    ports:
      - "5432:5432"
    networks:
      - privoxy-tor-backend-network
    # volumes:
      # - ./database/postgres.conf:/etc/postgresql/postgresql.conf
      # - ./database/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: postgres

  backend:
    build: 
      context: ./backend
      dockerfile: dockerfile
    image: test-app-backend
    container_name: backend
    volumes:
      - ./backend/app:/code/app
    environment:
      - DEBUG=True
    ports:
      - 5000:8000
    networks:
      - privoxy-tor-backend-network
    depends_on: 
      - privoxy
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000

  privoxy:
    container_name: privoxy
    build: ./privoxy
    networks:
      - privoxy-tor-backend-network
    ports:
      - 8118:8118
    restart: always

  tor:
    container_name: tor
    build:
      context: ./tor
      args:
        password: foo
    networks:
      - privoxy-tor-backend-network
    links:
      - backend
      - privoxy

  # scraper:
  #   container_name: scraper
  #   build: 
  #     context: ./scraper
  #   networks:
  #     - scraper-network

networks:
  privoxy-tor-backend-network:
  # scraper-network


