version: "3"

services:
  database:
    image: postgres:buster
    container_name: database
    ports:
      - "5432:5432"
    # volumes:
      # - ./database/postgres.conf:/etc/postgresql/postgresql.conf
      # - ./database/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: postgres

  backend:
    build: 
      context: ./backend
      dockerfile: dockerfile
    image: test-app-backend
    container_name: backend
    volumes:
      - ./backend/app:/code/app
    environment:
      - DEBUG=True
    ports:
      - 5000:8000
    depends_on: 
      - database
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000



      


