version: "3"

services:
  database:
    image: postgres:buster
    container_name: database
    ports:
      - "5432:5432"
    # volumes:
      # - ./database/postgres.conf:/etc/postgresql/postgresql.conf
      # - ./database/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: postgres

  backend:
    build: 
      context: ./backend
      dockerfile: dockerfile
    image: test-app-backend
    container_name: backend
    volumes:
      - ./backend/app:/code/app
    environment:
      - DEBUG=True
    ports:
      - 5000:8000
    depends_on: 
      - database
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000

  privoxy:
    container_name: privoxy
    build: ./privoxy
    networks:
      - privoxy-tor
    ports:
      - 8118:8118
    restart: always

  tor:
    container_name: tor
    build:
      context: ./tor
      args:
        password: foo
    networks:
      - privoxy-tor
    # links:
    #   - tor_controller
    #   - privoxy

  tor_controller:
    container_name: tor_controller
    build:
      context: ./tor_controller
    networks:
      - privoxy-tor
    ports:
      - 5001:5001
    volumes:
      - ./tor_controller:/code
    depends_on: 
      - tor
      - privoxy
    command: python app.py

networks:
  privoxy-tor:


