FROM python:3.8.5-buster
EXPOSE 5000

WORKDIR /code
ADD requirements.txt /code
RUN pip install -r requirements.txt
RUN apt-get update
RUN apt-get install -y curl 
RUN apt-get install -y iputils-ping

ADD . /code

